# Generated by Django 3.2.4 on 2021-06-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
